version: "3"

services:
  ##### FRONTEND SERVICES #####
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  ##### BACKEND SERVICES #####
  # onedrive:
  #   build:
  #     context: ./microservices/simple/onedrive
  #     dockerfile: Dockerfile
  #   environment:
  #     - AZURE_TENANT_ID
  #     - AZURE_CLIENT_ID
  #     - AZURE_CLIENT_SECRET_ID
  #     - PYTHONUNBUFFERED=1

  cv_parser:
    build:
      context: ./microservices/simple/cv_parser
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
  
  demand_survey:
    build:
      context: ./microservices/simple/demand_survey
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5003:5003"
  
  

  shortlist:
    build:
      context: ./microservices/complex/shortlist
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "9001:9001"

  candidates:
    build:
      context: ./microservices/complex/candidates
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "9002:9002"