services:
  ##### FRONTEND SERVICES #####
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"

  ##### BACKEND SERVICES #####
  sharepoint:
    build:
      context: ./microservices/simple/sharepoint
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - TENANT_ID=${TENANT_ID}
      - INTERNSHIP_SHAREPOINT_SITE=${INTERNSHIP_SHAREPOINT_SITE}
      - INTERNSHIP_SHAREPOINT_SITE_ID=${INTERNSHIP_SHAREPOINT_SITE_ID}
      - INTERNSHIP_SHAREPOINT_LIBRARY_NAME=${INTERNSHIP_SHAREPOINT_LIBRARY_NAME}
      - INTERNSHIP_SHAREPOINT_DRIVE_ID=${INTERNSHIP_SHAREPOINT_DRIVE_ID}

  cv_parser:
    build:
      context: ./microservices/simple/cv_parser
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
  
  demand_survey:
    build:
      context: ./microservices/simple/demand_survey
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5003:5003"
  
  eng_test:
    build:
      context: ./microservices/simple/eng_test
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5004:5004"

  shortlist:
    build:
      context: ./microservices/complex/shortlist
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "9001:9001"

  candidates:
    build:
      context: ./microservices/complex/candidates
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "9002:9002"