name: Docker Compose Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Compose validate
        uses: alexkainzinger/compose-action@v0.0.0 # using node20 see: https://github.com/isbang/compose-action/pull/37
        with:
          compose-file: docker-compose.yml

      - name: Docker configuration
        run: docker compose config


      